# Generated by Django 5.1 on 2024-08-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderName', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('preparing', 'Preparing'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], default='requested', max_length=10)),
            ],
        ),
    ]
