# Generated by Django 5.1 on 2024-08-29 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price'], 'verbose_name': 'Mart Product'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_name', models.CharField(max_length=100)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('products', models.ManyToManyField(related_name='orders', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='products.order')),
            ],
        ),
    ]
